---

  threshold:
    # [en_US]
    # Default value: 0.7
    #
    # [pt_BR]
    # Valor padr達o: 0.7
    default: 0.7


    # [en_US]
    # Default value: 0.9
    #
    # [pt_BR]
    # Valor padr達o: 0.9
    botao: 0.9

  
    # [en_US]
    # Default value: 0.9
    #
    # [pt_BR]
    # Valor padr達o: 0.9
    pao: 0.9

  
    # [en_US]
    # Default value: 0.9
    #
    # [pt_BR]
    # Valor padr達o: 0.9
    boneco: 0.9

